### ISSUE TITLE
数据集现在不公开了是为什么呢

### ISSUE THREAD

**Issue by Remaining** [gsh199449/productqa#1]

**Comment by gsh199449** [comment]
This dataset has already been published in January 2019. You can download the dataset by signing the copyright announcement with your name and organization, and complete the online form (link can be found at Readme). Next, you need to mail to us, we will send you the corpus by e-mail.

**Comment by Remaining** [comment]
Thank you, I have finished online form.



------------------ 原始邮件 ------------------
发件人: "GaoShen"<notifications@github.com>; 
发送时间: 2019年6月28日(星期五) 下午4:26
收件人: "gsh199449/productqa"<productqa@noreply.github.com>; 
抄送: "1975642935"<1975642935@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [gsh199449/productqa] 数据集现在不公开了是为什么呢 (#1)




This dataset has already been published in January 2019. You can download the dataset by signing the copyright announcement with your name and organization, and complete the online form (link can be found at Readme). Next, you need to mail to us, we will send you the corpus by e-mail.
